//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rentalEntities : DbContext
    {
        public rentalEntities()
            : base("name=rentalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<driver> drivers { get; set; }
        public virtual DbSet<feedback> feedbacks { get; set; }
        public virtual DbSet<registration> registrations { get; set; }
        public virtual DbSet<vehicle> vehicles { get; set; }
    }
}
